apiVersion: v1
kind: Pod
metadata:
  labels:
    app: agent-pod
spec:
  containers:
    - name: docker
      image: docker:19.03
      command:
        - cat
      tty: true
      privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: dockercert
          mountPath: /etc/docker/certs.d/docker.myweb.example.com/ca.cert
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: dockercert
      hostPath:
        path: /etc/docker/certs.d/docker.myweb.example.com/ca.cert  