---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prueba-deployment
  name: prueba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prueba
  template:
    metadata:
      labels:
        app: prueba
    spec:
      containers:
      - name: prueba
        image: docker.myweb.example.com/prueba:${BUILD_NUMBER}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prueba
  name: prueba-service
spec:
  selector:
    app: prueba
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  