---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prueba
  name: prueba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prueba
  template:
    metadata:
      labels:
        app: prueba
    spec:
      containers:
      - image: docker.myweb.example.com/prueba:1
        imagePullPolicy: Always
        name: prueba

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prueba
  name: prueba
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: prueba
  type: NodePort
